# Generated by Django 3.2.3 on 2021-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_main_abouttxt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='main',
            name='tw',
        ),
        migrations.RemoveField(
            model_name='main',
            name='yt',
        ),
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='insta',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='twiteer',
            field=models.URLField(default=''),
        ),
    ]
